APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:ytLrDyIbZNs3wI6p5BzSbzMbsrE1LkP/ce0XwJo8sSU=
APP_DEBUG=true
APP_URL=http://hatirpal.com

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sagoreweb
DB_USERNAME=Shakil
DB_PASSWORD=01742214318

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=cookie
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=d25ce03bdc2f1f
MAIL_PASSWORD=e69bea51eb6a95
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDRESS=mehrabhoussainshakil12@gmail.com
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"




<?php
$targetFolder=$_SERVER['DOCUMENT_ROOT'].'storage/app/public';
$linktFolder=$_SERVER['DOCUMENT_ROOT'].'public/storage';
symlink($targetFolde,$linktFolder);
echo 'Success';
?>